name: Release Post to X
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Release Post to X
        uses: captradeoff/x-post-action@v1.2
        with:
          message: | 
            ${{ github.event.repository.name }} Version ${{ github.event.release.tag_name }} has been released! Check out the release notes: ${{ github.event.release.html_url }}
          appKey: ${{ secrets.X_API_KEY }}
          appSecret: ${{ secrets.X_API_KEY_SECRET }}
          accessToken: ${{ secrets.X_ACCESS_TOKEN }}
          accessSecret: ${{ secrets.X_ACCESS_TOKEN_SECRET }}